sd_webui: add DIB_SD_WEBUI_DATA_FILE in image

diff --git a/sd-webui-common/bin/start_sd_webui b/sd-webui-common/bin/start_sd_webui
--- a/sd-webui-common/bin/start_sd_webui
+++ b/sd-webui-common/bin/start_sd_webui
@@ -4,8 +4,9 @@ set -e
 SD_WEBUI_DIR=${SD_WEBUI_DIR:-"/root/stable-diffusion-webui"}
 SD_WEBUI_DATA_DIR=${SD_WEBUI_DATA_DIR:-"${SD_WEBUI_DIR}"}
 SD_WEBUI_PORT=${SD_WEBUI_PORT:-"10000"}
-SD_WEBUI_DATA_TAR=${SD_WEBUI_DATA_TAR:-"/root/public/sd_webui/sd_webui_20240201_data.tar.xz"}
+SD_WEBUI_DATA_TAR=${SD_WEBUI_DATA_TAR:-"/root/sd_webui_data.tar.xz"}
 SD_WEBUI_DATA_VOLUME=${SD_WEBUI_DATA_VOLUME:-"/root/data/"}
+SD_WEBUI_PUBLIC_DATA=${SD_WEBUI_PUBLIC_DATA:-"/root/public/sd_webui/data"}
 
 CACHE=${SD_WEBUI_DIR}/.cache
 CLIP_CACHE=${CACHE}/clip
@@ -16,13 +17,41 @@ export TRANSFORMERS_CACHE=${HF_HOME}/transformers
 
 # check if venv is a link file
 if [ -L "${SD_WEBUI_DIR}/venv" ]; then
-    # if target of link is not a directory
-    if [ ! -d "$(readlink "${SD_WEBUI_DIR}/venv")" ]; then
+    # if target of link is not a directory, that means we can do fresh install
+    if [ ! -d "$(readlink "${SD_WEBUI_DIR}/venv")" ] && [ -f "${SD_WEBUI_DATA_TAR}" ]; then
         echo "Uncompressing data from ${SD_WEBUI_DATA_TAR} to ${SD_WEBUI_DATA_VOLUME}"
+
+        # check if the target data dir is not empty
+        target=${SD_WEBUI_DATA_VOLUME}/stable-diffusion-webui
+        if [ ! -z "$(ls -A ${target})" ]; then
+            # prompt for confirmation
+            read -p "Target dir ${target} is not empty, do you want to continue? (y/N) " -n 1 -r REPLY && echo
+            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+                echo "Aborted"
+                exit 1
+            fi
+        fi
         tar -xf "${SD_WEBUI_DATA_TAR}" -C "${SD_WEBUI_DATA_VOLUME}" \
             --checkpoint=$(($(stat -c %s "${SD_WEBUI_DATA_TAR}") / 512 / 20 / 100)) \
             --checkpoint-action=. &&
             echo "Done"
+
+        # sync controlnet models
+        if [ -d "${SD_WEBUI_PUBLIC_DATA}" ]; then
+            echo "Syncing controlnet models"
+            rclone sync --progress \
+                "${SD_WEBUI_PUBLIC_DATA}/models/ControlNet" \
+                "${target}/models/ControlNet"
+        fi
+
+    else
+        # check all link files in ${SD_WEBUI_DIR}, if link target dir not exist, create the target dir
+        for f in $(find "${SD_WEBUI_DIR}" -type l); do
+            target="$(readlink "${f}")"
+            if [ ! -d "${target}" ]; then
+                mkdir -p "${target}"
+            fi
+        done
     fi
 fi
 
